### ISSUE TITLE
Tuesday, November 1st 2016 

### ISSUE THREAD

**Issue by jendiamond** [LAXercism/mobprogramminglax#7]
@jendiamond @jennykimmy @Taekyoon @alex1100 Brandon Eliza

---

@kytrinyx  
We just ran the tests and found that all 5 tests now break at the login section.   
They previously did not break.
We are wondering if something changed to cause this beak that we should be aware of.

**`test/acceptance/team_test.rb`**
```
EI, [2016-11-02T23:22:52.149297 #23791]  INFO -- : get http://x.exercism.io/v3/tracks
D, [2016-11-02T23:22:52.150080 #23791] DEBUG -- request: User-Agent: "github.com/exercism/exercism.io"
I, [2016-11-02T23:22:57.103145 #23791]  INFO -- Status: 200
D, [2016-11-02T23:22:57.104165 #23791] DEBUG -- response: server: "Cowboy"
date: "Wed, 02 Nov 2016 23:22:52 GMT"
connection: "close"
content-type: "application/json;charset=utf-8"
x-content-type-options: "nosniff"
content-length: "518125"
via: "1.1 vegur"
EEEE

Fabulous run in 14.018774s, 0.3567 runs/s, 0.0000 assertions/s.

  1) Error:
TeamAcceptanceTest#test_managing_a_team_as_sole_manager:
Capybara::ElementNotFound: Unable to find link or button "Account"
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/actions.rb:13:in `click_link_or_button'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /vagrant/exercism.io/test/acceptance/team_test.rb:32:in `block in test_managing_a_team_as_sole_manager'
    /vagrant/exercism.io/test/acceptance/acceptance_test_case.rb:14:in `block in with_login'


  2) Error:
TeamAcceptanceTest#test_joining_a_team:
Capybara::ElementNotFound: Unable to find link or button "Account"
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/actions.rb:13:in `click_link_or_button'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /vagrant/exercism.io/test/acceptance/team_test.rb:14:in `block in test_joining_a_team'
    /vagrant/exercism.io/test/acceptance/acceptance_test_case.rb:14:in `block in with_login'


  3) Error:
TeamAcceptanceTest#test_request_and_accept_membership_during_search:
Capybara::ElementNotFound: Unable to find css "div[data-team-slug=\"abc\"]"
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:287:in `within'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /vagrant/exercism.io/test/acceptance/team_test.rb:73:in `block in test_request_and_accept_membership_during_search'
    /vagrant/exercism.io/test/acceptance/acceptance_test_case.rb:14:in `block in with_login'


  4) Error:
TeamAcceptanceTest#test_search_for_public_teams:
Capybara::ElementNotFound: Unable to find css ".teams-result-list"
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:287:in `within'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /vagrant/exercism.io/test/acceptance/team_test.rb:55:in `block in test_search_for_public_teams'
    /vagrant/exercism.io/test/acceptance/acceptance_test_case.rb:14:in `block in with_login'


  5) Error:
TeamAcceptanceTest#test_team_pagination:
Capybara::ElementNotFound: Unable to find link "2"
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/node/actions.rb:26:in `click_link'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /vagrant/exercism.io/vendor/bundle/ruby/2.2.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /vagrant/exercism.io/test/acceptance/team_test.rb:135:in `block in test_team_pagination'
    /vagrant/exercism.io/test/acceptance/acceptance_test_case.rb:14:in `block in with_login'

```

**Comment by jendiamond** [comment]
Running the "write to page.html" created nothing...

![screenshot from 2016-11-02 15 56 31](https://cloud.githubusercontent.com/assets/751697/19950498/14a40abc-a115-11e6-83f6-5c21404869d0.png)
More below...
![screencapture-file-home-jendiamond-desktop-groundwork-exercism-io-page-html-1478127117170](https://cloud.githubusercontent.com/assets/751697/19950404/7245cd32-a114-11e6-93dd-5e233a8d69a9.png)

**Comment by kytrinyx** [comment]
> We just ran the tests and found that all 5 tests now break at the login section.

The tests are not failing on master. Can you say more about the context of these failing tests?
